### ISSUE TITLE
Add auth before making database updates

### ISSUE THREAD

**Issue by metalandcoffee** [metalandcoffee/in-the-queue-app#24]

**Comment by eboniebutler** [comment]
https://auth0.github.io/nextjs-auth0/modules/helpers_with_api_auth_required.html

**Comment by metalandcoffee** [comment]
Protected API endpoints using https://www.npmjs.com/package/@auth0/nextjs-auth0 ✨

Conditionally show and hide add/edit functionality.

All done!
